# config_manager.py
import datetime
import traceback
from database_manager import DatabaseManager

TABLA_SQL = """
CREATE TABLE CONFIGURACIONES_NOMBRE_ARCHIVOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE_CONFIG VARCHAR(100) NOT NULL,
    FORMATO_XML VARCHAR(255),
    FORMATO_PDF VARCHAR(255),
    FORMATO_CUV VARCHAR(255),
    FORMATO_JSON VARCHAR(255),
    ACTIVA SMALLINT DEFAULT 0,
    FECHA_CREACION TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP
)
"""

CREATE_INDEX_UNIQUE = """
CREATE UNIQUE INDEX UX_CONFIG_NOMBRE ON CONFIGURACIONES_NOMBRE_ARCHIVOS (NOMBRE_CONFIG)
"""

def ensure_table_exists():
    db = DatabaseManager()
    conn = None
    cur = None
    try:
        conn = db.get_connection()
        cur = conn.cursor()
        cur.execute("SELECT COUNT(1) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'CONFIGURACIONES_NOMBRE_ARCHIVOS'")
        if cur.fetchone()[0] == 0:
            cur.execute(TABLA_SQL)
            try:
                cur.execute(CREATE_INDEX_UNIQUE)
            except Exception:
                # Ignorar si el índice ya existe
                pass
            conn.commit()
    except Exception as e:
        raise
    finally:
        if cur:
            cur.close()

def create_config(nombre, formato_xml=None, formato_pdf=None, formato_cuv=None, formato_json=None, activar=False):
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        now = datetime.datetime.now()
        cur.execute("""
            INSERT INTO CONFIGURACIONES_NOMBRE_ARCHIVOS
            (NOMBRE_CONFIG, FORMATO_XML, FORMATO_PDF, FORMATO_CUV, FORMATO_JSON, ACTIVA, FECHA_CREACION, FECHA_ACTUALIZACION)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, (nombre, formato_xml, formato_pdf, formato_cuv, formato_json, 1 if activar else 0, now, now))
        
        if activar:
            cur.execute("UPDATE CONFIGURACIONES_NOMBRE_ARCHIVOS SET ACTIVA = 0 WHERE NOMBRE_CONFIG <> ?", (nombre,))
        
        conn.commit()
        return True
    except Exception as e:
        conn.rollback()
        raise
    finally:
        if cur:
            cur.close()

def update_config(id_, nombre=None, formato_xml=None, formato_pdf=None, formato_cuv=None, formato_json=None, activar=None):
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        now = datetime.datetime.now()
        # construir update dinámico
        updates = []
        params = []
        if nombre is not None:
            updates.append("NOMBRE_CONFIG = ?"); params.append(nombre)
        if formato_xml is not None:
            updates.append("FORMATO_XML = ?"); params.append(formato_xml)
        if formato_pdf is not None:
            updates.append("FORMATO_PDF = ?"); params.append(formato_pdf)
        if formato_cuv is not None:
            updates.append("FORMATO_CUV = ?"); params.append(formato_cuv)
        if formato_json is not None:
            updates.append("FORMATO_JSON = ?"); params.append(formato_json)
        updates.append("FECHA_ACTUALIZACION = ?"); params.append(now)
        if updates:
            sql = "UPDATE CONFIGURACIONES_NOMBRE_ARCHIVOS SET " + ", ".join(updates) + " WHERE ID = ?"
            params.append(id_)
            cur.execute(sql, params)
        if activar is True:
            cur.execute("UPDATE CONFIGURACIONES_NOMBRE_ARCHIVOS SET ACTIVA = 0 WHERE ID <> ?", (id_,))
            cur.execute("UPDATE CONFIGURACIONES_NOMBRE_ARCHIVOS SET ACTIVA = 1 WHERE ID = ?", (id_,))
        elif activar is False:
            cur.execute("UPDATE CONFIGURACIONES_NOMBRE_ARCHIVOS SET ACTIVA = 0 WHERE ID = ?", (id_,))
        conn.commit()
        return True
    except Exception as e:
        conn.rollback()
        raise
    finally:
        if cur:
            cur.close()

def delete_config(id_):
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM CONFIGURACIONES_NOMBRE_ARCHIVOS WHERE ID = ?", (id_,))
        conn.commit()
        return True
    except Exception as e:
        conn.rollback()
        raise
    finally:
        if cur:
            cur.close()

def list_configs():
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        cur.execute("SELECT ID, NOMBRE_CONFIG, FORMATO_XML, FORMATO_PDF, FORMATO_CUV, FORMATO_JSON, ACTIVA, FECHA_CREACION, FECHA_ACTUALIZACION FROM CONFIGURACIONES_NOMBRE_ARCHIVOS ORDER BY ID")
        rows = cur.fetchall()
        # mapear a dicts
        results = []
        for r in rows:
            results.append({
                'id': r[0],
                'nombre': r[1],
                'formato_xml': r[2],
                'formato_pdf': r[3],
                'formato_cuv': r[4],
                'formato_json': r[5],
                'activa': bool(r[6]),
                'fecha_creacion': r[7],
                'fecha_actualizacion': r[8]
            })
        return results
    except Exception as e:
        raise
    finally:
        if cur:
            cur.close()

def get_config_by_id(id_):
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        cur.execute("SELECT ID, NOMBRE_CONFIG, FORMATO_XML, FORMATO_PDF, FORMATO_CUV, FORMATO_JSON, ACTIVA FROM CONFIGURACIONES_NOMBRE_ARCHIVOS WHERE ID = ?", (id_,))
        r = cur.fetchone()
        if r:
            return {
                'id': r[0],
                'nombre': r[1],
                'formato_xml': r[2],
                'formato_pdf': r[3],
                'formato_cuv': r[4],
                'formato_json': r[5],
                'activa': bool(r[6])
            }
        return None
    except Exception as e:
        raise
    finally:
        if cur:
            cur.close()

def get_active_config():
    ensure_table_exists()
    db = DatabaseManager()
    conn = db.get_connection()
    cur = None
    try:
        cur = conn.cursor()
        cur.execute("SELECT ID, NOMBRE_CONFIG, FORMATO_XML, FORMATO_PDF, FORMATO_CUV, FORMATO_JSON FROM CONFIGURACIONES_NOMBRE_ARCHIVOS WHERE ACTIVA = 1")
        r = cur.fetchone()
        if r:
            return {
                'id': r[0],
                'nombre': r[1],
                'formato_xml': r[2],
                'formato_pdf': r[3],
                'formato_cuv': r[4],
                'formato_json': r[5]
            }
        return None
    except Exception as e:
        raise
    finally:
        if cur:
            cur.close()